const {
  signUpSellerValidation,
  loginsellerValidation,
  accessTokenVarify,
  adderssValidation,
  profileValidation,
  productValidation,
  checkRole,
  uploadfile,
  uploadImage,
  deleteImageFromCloud,
  checkFilter,
  productUpdateValidation,
  uploadImage1,
  uploadfileInCloud,
  addCartValidation,
  incrementCartValidation,
  checkPublicRole,
  reviewValidation,
  reviewDeleteValidation,
  editReviewValidation,
  uploadFileToCloud,
  checkIdFormat
} = require('./seller.middleware');
const {
  adminValidation,
  categoryValidation,
  brandValidation,
  orderValidation,
  createOrderValidation,
} = require('./admin.middleware');

module.exports = {
  signUpSellerValidation,
  loginsellerValidation,
  adminValidation,
  accessTokenVarify,
  adderssValidation,
  profileValidation,
  productValidation,
  checkRole,
  uploadfile,
  uploadImage,
  deleteImageFromCloud,
  checkFilter,
  productUpdateValidation,
  categoryValidation,
  brandValidation,
  uploadImage1,
  uploadfileInCloud,
  addCartValidation,
  incrementCartValidation,
  orderValidation,
  createOrderValidation,
  checkPublicRole,
  reviewValidation,
  reviewDeleteValidation,
  editReviewValidation,
  uploadFileToCloud,
  checkIdFormat
};
