const {
  signUpSellerValidation,
  loginsellerValidation,
  accessTokenVarify,
  adderssValidation,
  profileValidation,
  productValidation,
  productUpdateValidation,
  addCartValidation,
  incrementCartValidation,
  reviewValidation,
  reviewDeleteValidation,
  editReviewValidation,
  adminValidation,
  categoryValidation,
  brandValidation,
  orderValidation,
  createOrderValidation,
} = require('./seller.validate');

module.exports = {
  signUpSellerValidation,
  loginsellerValidation,
  accessTokenVarify,
  adderssValidation,
  profileValidation,
  productValidation,
  productUpdateValidation,
  addCartValidation,
  incrementCartValidation,
  reviewValidation,
  reviewDeleteValidation,
  editReviewValidation,
  adminValidation,
  categoryValidation,
  brandValidation,
  orderValidation,
  createOrderValidation,
};